services:
  backend:
    build:
      context: ./back/app/
    restart: on-failure
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front/
    restart: on-failure
    ports:
      - "3000:3000"
